
from sh import Sh  # this is the local sh module

VBoxManage = Sh('VboxManage')
blockdiag = Sh('blockdiag')
cat = Sh('cat')
cm = Sh('cm')
fgmetric = Sh('fgmetric')
fgrep = Sh('fgrep')
gchproject = Sh('gchproject')
gchuser = Sh('gchuser')
git = Sh('git')
glusers = Sh('glusers')
gmkproject = Sh('gmkproject')
grep = Sh('grep')
gstatement = Sh('gstatement')
head = Sh('head')
keystone = Sh('keystone')
kill = Sh('kill')
ls = Sh('ls')
mkdir = Sh('mkdir', args='-p')
mongod = Sh('mongod')
mongoimport = Sh('mongoimport')
mysql = Sh('mysql')
nosetests = Sh('nosetests')
nova = Sh('nova')
ping = Sh('ping')
pwd = Sh('pwd')
rackdiag = Sh('rackdiag')
rm = Sh('rm')
rsync = Sh('rsync')
scp = Sh('scp')
sorted = Sh('sort')
ssh = Sh('ssh')
sudo = Sh('sudo')
tail = Sh('tail')
vagrant = Sh('vagrant')
which = Sh('which')
